development:
    dialect: postgres
    datasource: host=regulus_db port=5432 dbname=regulusdb user=regulus password=regulus sslmode=disable
    dir: resources/db/migrations/postgres

production:
    dialect: postgres
    datasource: host=127.0.0.1 port=5432 dbname=regulusdb user=regulus password=regulus sslmode=disable
    dir: resources/db/migrations/postgres