// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	GorpMigrations string
	Maker          string
	Staff          string
	StaffGroup     string
}{
	GorpMigrations: "gorp_migrations",
	Maker:          "maker",
	Staff:          "staff",
	StaffGroup:     "staff_group",
}
